examples/demo_rolling.py, mani_skill2/agents/robots/rolling_pin.py, mani_skill2/envs/mpm/rolling_env.py, mani_skill2/envs/mpm/test/test_rolling_env.py
This PR adds a simulation environment `rolling_env.py`.
The main feature is that the robot (rolling pin) is not an "articulation" (robot with revolute/prismatic joint under PD control), but a free-floating single rigid body. We apply a wrench on this rolling pin directly.
Currently the dough seems quite stiff. It doesn't deform much under the pressure of the rolling pin. This could be because that the rolling pin controller is not stiff enough.
In the next PR I will try one-way coupling, that the rolling pin just follows a prescribed trajectory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/maniskill2/1)
=> Add rolling pin

examples/demo_rolling.py, mani_skill2/envs/mpm/rolling_env.py, mani_skill2/envs/mpm/test/test_rolling_env.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/maniskill2/2)
=> Compute heightmap of the dough.

mani_skill2/envs/mpm/rolling_env.py, mani_skill2/envs/mpm/test/test_rolling_env.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/maniskill2/3)
=> Add step function in RollingPinEnv

mani_skill2/envs/mpm/rolling_env.py, mani_skill2/envs/mpm/test/test_rolling_env.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/maniskill2/4)
=> Lift the rolling pin after sweeping.

examples/demo_rolling.py, examples/dough_model_learning/data_generation.py, examples/dough_model_learning/test/test_data_generation.py, mani_skill2/envs/mpm/rolling_env.py, mani_skill2/envs/mpm/test/test_rolling_env.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/maniskill2/5)
=> Add a function to generate state_action tuple data for dough rolling.

examples/dough_model_learning/data_generation.py, examples/dough_model_learning/test/test_data_generation.py, mani_skill2/envs/mpm/rolling_env.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/6)
=> Add TransitionTupleDataset

.gitignore, examples/demo_rolling.py, examples/dough_model_learning/data_generation.py, examples/dough_model_learning/test/test_data_generation.py, mani_skill2/envs/mpm/rolling_env.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/7)
=> Update code formatting to black, format docstrings, update gitignore

.gitignore, environment.yml, examples/dough_model_learning/config/film_unet.yaml, examples/dough_model_learning/train.py, mani_skill2/data/rllib_data_utils.py, mani_skill2/data/sample_batch_dataset.py, mani_skill2/dynamics/base.py, mani_skill2/dynamics/modules.py, mani_skill2/dynamics/network_dynamics_model.py, mani_skill2/dynamics/networks.py, mani_skill2/tests/data/test_rllib_data_utils.py, mani_skill2/tests/data/test_sample_batch_dataset.py, mani_skill2/tests/dynamics/test_modules.py, mani_skill2/tests/dynamics/test_network_dynamics_model.py, mani_skill2/tests/dynamics/test_networks.py, mani_skill2/tests/envs/mpm/test_rolling_env.py, mani_skill2/utils/testing/dynamics_test_utils.py, mani_skill2/utils/testing/rllib_test_utils.py
This PR combines two commits.
The first commit defines a DynamicsModel base class
along with a network (a U-net), and a DynamicsModel
subclass that wraps a network.
The second commit adds pytorch lightning code 
(a module for training DynamicsModels), and the
script and config used to train the models.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/12)
=> Add modeling and training code

.github/workflows/python-app.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/14)
=> github action runs on self-hosted machine.

.github/workflows/python-app.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/15)
=> github runner CI uses local python interpreter.

.github/workflows/python-app.yml, mani_skill2/data/rllib_data_utils.py, mani_skill2/data/sample_batch_dataset.py, mani_skill2/dynamics/networks.py, mani_skill2/tests/envs/mpm/test_rolling_env.py, mani_skill2/tests/utils/test_rollout.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/16)
=> Try to make CI happy.

mani_skill2/dynamics/base.py, mani_skill2/dynamics/generative_env.py, mani_skill2/dynamics/modules.py, mani_skill2/dynamics/network_dynamics_model.py, mani_skill2/dynamics/reward.py, mani_skill2/tests/dynamics/test_generative_env.py, mani_skill2/tests/dynamics/test_network_dynamics_model.py, mani_skill2/utils/testing/dynamics_test_utils.py
Also modify the API for DynamicsModel, that step() function takes state/action and returns the next state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/17)
=> Add the abstract GenerativeEnv

.github/workflows/python-app.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/20)
=> CI sets python path

.github/workflows/python-app.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/21)
=> github action echos pythonpath

mani_skill2/algorithms/gradient_shooting.py, mani_skill2/dynamics/base.py, mani_skill2/dynamics/generative_env.py, mani_skill2/tests/algorithms/test_gradient_shooting.py, mani_skill2/tests/dynamics/test_generative_env.py, mani_skill2/utils/testing/dynamics_test_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/19)
=> Add GradientShootingAgent

mani_skill2/algorithms/action_samplers.py, mani_skill2/algorithms/gradient_shooting.py, mani_skill2/algorithms/gym_agent.py, mani_skill2/algorithms/random_shooting.py, mani_skill2/dough_model_learning/config/film_unet.yaml, mani_skill2/dough_model_learning/dough_reward_models.py, mani_skill2/dough_model_learning/eval.py, mani_skill2/dough_model_learning/generate_dough_rolling_data.py, mani_skill2/dough_model_learning/visualize_rollouts.py, mani_skill2/dynamics/generative_env.py, mani_skill2/dynamics/networks.py, mani_skill2/envs/mpm/rolling_env.py, mani_skill2/tests/algorithms/test_action_samplers.py, mani_skill2/tests/algorithms/test_random_shooting.py, mani_skill2/tests/utils/test_rollout.py, mani_skill2/utils/rollout.py, mani_skill2/utils/testing/dynamics_test_utils.py
This commit glues together the code to run eval.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/22)
=> Implement evaluation of an algorithm and a trained model

mani_skill2/dough_model_learning/config/film_unet.yaml, mani_skill2/dough_model_learning/data_generation_utils.py, mani_skill2/dough_model_learning/dough_reward_models.py, mani_skill2/dough_model_learning/eval.py, mani_skill2/dough_model_learning/generate_dough_rolling_data.py, mani_skill2/dough_model_learning/train.py, mani_skill2/dough_model_learning/visualize_rollouts.py, mani_skill2/dynamics/base.py, mani_skill2/dynamics/modules.py, mani_skill2/dynamics/network_dynamics_model.py, mani_skill2/dynamics/normalizers.py, mani_skill2/dynamics/visualizers.py, mani_skill2/envs/mpm/rolling_env.py, mani_skill2/tests/dynamics/test_network_dynamics_model.py, mani_skill2/tests/dynamics/test_normalizers.py, mani_skill2/utils/testing/dynamics_test_utils.py
This commit improves dynamics model training by:
1. Adding normalization of model inputs / outputs
2. Logging visualizations of predictions during training
3. Changing the action distribution during data generation to match that used during evaluation
Given those changes, planning using random shooting with a learned model consistently outperforms planning with a random model, and seems to "work".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/23)
=> Improve dynamics model training

mani_skill2/algorithms/gradient_shooting.py, mani_skill2/tests/algorithms/test_gradient_shooting.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/24)
=> GradientShooting works on a batch of action sequences.

mani_skill2/dough_model_learning/dough_reward_models.py, mani_skill2/tests/dough_model_learning/test_dough_reward_models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/25)
=> Add EllipseShapeRewardModel.

mani_skill2/algorithms/action_samplers.py, mani_skill2/algorithms/gradient_shooting.py, mani_skill2/algorithms/random_shooting.py, mani_skill2/dough_model_learning/dough_reward_models.py, mani_skill2/dynamics/base.py, mani_skill2/envs/mpm/rolling_env.py, mani_skill2/tests/algorithms/test_gradient_shooting.py, mani_skill2/tests/dough_model_learning/test_dough_reward_models.py, mani_skill2/tests/envs/mpm/test_rolling_env.py
1. Clip the action.
2. Fix the memory leak issue with backward(retain_graph=True)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/26)
=> Test GradientShooting.

environment.yml, mani_skill2/dough_model_learning/config/film_unet.yaml, mani_skill2/dough_model_learning/train.py, mani_skill2/dynamics/visualizers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hongkai-dai/ManiSkill2/33)
=> Add wandb logging
